output_dir: 'demo/JUN/embeddings'
module: src.experiments.image_embeddings
class: ImageEmbeddingExperimentCustomSplit
run_params:
  data_config: {'nuclei_image_dir':'demo/JUN/images/preprocessed/padded_nuclei',
                      'train_nuclei_metadata_file':'demo/JUN/images/preprocessed/padded_nuclei_metadata.csv.gz',
                      'val_nuclei_metadata_file':'demo/JUN/images/preprocessed/padded_nuclei_metadata.csv.gz',
                      'test_nuclei_metadata_file':'demo/JUN/images/preprocessed/padded_nuclei_metadata.csv.gz',
                      'slide_image_dir': 'demo/JUN/images/raw',
                      'data_key':'images', 'label_key':'label', 'index_key':'image_file',
                      'pseudo_rgb':True}

  model_config: {'model_config':{
                        'type':'ensemble',
                        'input_dim': 1024,
                        'latent_dim': 1024,
                        'n_output_nodes': 41,
                        'component_dicts':[
                                {'type':'ResNet18', 'pretrained':True, 'n_output_nodes':512,
                                 fix_feature_extractor: False, 'dropout_rate':0.0},
                                {'type':'ResNet18', 'pretrained':True, 'n_output_nodes':512,
                                 fix_feature_extractor: False, 'dropout_rate':0.0}
                        ]
                 },
                 'optimizer_config':{'type':'adam','lr':0.00001, 'weight_decay':0.001},
                 'loss_config':{'type':'ce'}}

  domain_name: 'image'
  num_epochs: 300
  early_stopping: 5
  batch_size: 64
  random_state: 1234
  save_freq: 50

pipeline:
  - method: initialize_image_data_set
    params:
      multi_image: True
  - method: initialize_data_transform_pipeline
    params:
      data_transform_pipelines: ["nuclei_image", "slide_image"]
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
  - method: load_model
    params:
      weights_fname: "demo/JUN/models/image_encoder_weights.pth"
  - method: extract_and_save_latents
    params:
      dataset_types: ["test"]

