output_dir: "data/experiments/image_preprocessing"
module: "src.preprocessing.image_preprocessing"
class: "ImageDatasetPreprocessor"

run_params:
  image_input_dir: "data/images/raw/"
  metadata_file: "data/experiments/image_preprocessing/filtering/filtered_image_metadata.csv"
  raw_image_col_name: "Image_FileName_OrigHoechst"
  illum_image_col_name: "Image_FileName_IllumHoechst"
  plate_col_name: "Image_Metadata_Plate"
  well_col_name: "Image_Metadata_Well"

pipeline:
  - method: segment_all_images_given_outlines
    params:
      outline_input_dir: "data/images/segmented_outlines"
      nuclei_outline_col_name: "Image_FileName_NucleiOutlines"
      min_area: 100
      fill_holes: 16



