output_dir: "data/experiments/image_preprocessing"
module: "src.preprocessing.image_preprocessing"
class: "ImageDatasetPreprocessor"

run_params:
  image_input_dir: "data/images/raw/"
  metadata_file: "data/experiments/image_preprocessing/filtering/filtered_image_metadata.csv"
  raw_image_col_name: "Image_FileName_OrigHoechst"
  illum_image_col_name: "Image_FileName_IllumHoechst"
  plate_col_name: "Image_Metadata_Plate"
  well_col_name: "Image_Metadata_Well"

pipeline:
  - method: segment_all_images_given_outlines
    params:
      outline_input_dir: "data/images/segmented_outlines"
      nuclei_outline_col_name: "Image_FileName_NucleiOutlines"
      min_area: 100
      fill_holes: 16

#  - method: save_padded_images
#    params:
#      input_dir: "data/experiments/preprocessing_0518/segmented_nuclei"
#      target_size: [92,92]
#  - method: add_gene_label_column_to_metadata
#    params:
#      nuclei_metadata_file: "data/images/nuclei_metadata.csv"
#  - method: resize_and_save_images
#    params:
#      input_dir: "data/images/padded_nuclei"
#      target_size: [64,64]



