output_dir: "data/experiments/image_preprocessing"
module: "src.preprocessing.image_preprocessing"
class: "ImageDatasetPreprocessor"

run_params:
  image_input_dir: "data/images/raw/"
  metadata_file: "data/experiments/image_preprocessing/filtering/filtered_image_metadata.csv"
  raw_image_col_name: "Image_FileName_OrigHoechst"
  illum_image_col_name: "Image_FileName_IllumHoechst"
  plate_col_name: "Image_Metadata_Plate"
  well_col_name: "Image_Metadata_Well"

pipeline:
  - method: save_padded_images
    params:
      nuclei_metadata_file: "data/experiments/image_preprocessing/cropped_nuclei_unet_seg/nuclei_metadata.csv"
      input_dir: "data/experiments/image_preprocessing/cropped_nuclei_unet_seg/nuclei_images"
      target_size: [64,64]
  - method: add_gene_label_column_to_metadata
#  - method: resize_and_save_images
#    params:
#      input_dir: "data/images/padded_nuclei"
#      target_size: [64,64]



