output_dir: 'data/experiments/image_embeddings'
module: src.experiments.train_model
class: TrainModelExperiment
run_params:
  data_config: {'image_dir':'data/experiments/image_preprocessing/full_pipeline/padded_nuclei',
                      'metadata_file':'data/experiments/image_preprocessing/full_pipeline/padded_nuclei_metadata.csv',
                      'data_key':'image', 'label_key':'label', 'extra_feature_key':'nuclei_density',
                      'target_list':["ARNTL", "ATG5", "BAX", "CASP8", "CCND1", "CEBPA", "DVL2", "ERG", "JUN"],
                      'pseudo_rgb':True}

  model_config: {'model_config':{'type':'ResNet18', 'pretrained':True, 'n_output_nodes':9,
                                 'fix_feature_extractor': False, 'n_extra_features': 1, 'dropout_rate':0.0},
                       'optimizer_config':{'type':'adam','lr':0.00001, 'weight_decay':0.0005},
                       'loss_config':{'type':'ce'}}

  domain_name: 'image'
  num_epochs: 300
  early_stopping: 10
  train_val_test_split: [0.7, 0.2, 0.1]
  batch_size: 32
  random_state: 1234
  save_freq: 50

pipeline:
  - method: initialize_image_data_set
  - method: initialize_data_loader_dict
    params:
      data_transform_pipeline: "imagenet_extended_random"
  - method: initialize_domain_config
  - method: train_models
  - method: visualize_loss_evolution

