output_dir: 'data/experiments/image_embeddings/jump/specificity_target_emb_cv_strat/fold_0/'
module: src.experiments.image_embeddings
class: ImageEmbeddingExperimentCustomSplit
run_params:
  data_config: {'nuclei_image_dir':'data/experiments/image_preprocessing/jump/full_pipeline/padded_nuclei',
                      'train_nuclei_metadata_file':'data/experiments/image_preprocessing/jump/specific_targets_cv_stratified/nuclei_md_train_fold_0.csv',
                      'val_nuclei_metadata_file':'data/experiments/image_preprocessing/jump/specific_targets_cv_stratified/nuclei_md_val_fold_0.csv',
                      'test_nuclei_metadata_file':'data/experiments/image_preprocessing/jump/specific_targets_cv_stratified/nuclei_md_test_fold_0.csv',
                      'slide_image_dir': 'data/images/jump/illum_corrected',
                      'data_key':'slide_image', 'label_key':'label', 'index_key':'image_file',
                      'pseudo_rgb':True,
                      'plate_col': 'batch',}

  model_config: {'model_config':{
                        'type':'ResNet18',
                        'pretrained': True,
                        'fix_feature_extractor': False,
                        'n_output_nodes': 32,
                 },
                 'optimizer_config':{'type':'adam','lr':0.00001, 'weight_decay':0.0005},
                 'loss_config':{'type':'ce'}}

  domain_name: 'image'
  num_epochs: 300
  early_stopping: 5
  batch_size: 64
  random_state: 1234
  save_freq: 50

pipeline:
  - method: initialize_image_data_set
    params:
      multi_image: True
  - method: initialize_data_transform_pipeline
    params:
      data_transform_pipelines: ["nuclei_image", "slide_image"]
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
#  - method: load_model
#    params:
#      weights_fname: "data/experiments/image_embeddings/specificity_target_emb_cv_strat/fold_0/best_model_weights.pth"
  - method: train_models
  - method: evaluate_test_performance
  - method: visualize_loss_evolution
  - method: plot_confusion_matrices
    params:
      normalize: "true"
  - method: extract_and_save_latents

