output_dir: 'data/experiments/morph_embeddings'
module: src.experiments.train_model
class: TrainModelExperiment
run_params:
  data_config: {'feature_label_file':'data/experiments/image_preprocessing/full_pipeline/nuclei_ncmo_features.csv.gz',
                      'data_key':'profile', 'label_key':'label',
                      'label_col':'gene_symbol',
                      'target_list':["ARNTL", "ATG5", "BAX", "CASP8", "CCND1", "CEBPA", "DVL2", "ERG", "JUN"],
                      'exclude_features':['image_file', 'gene_id', 'centroid-0', 'centroid-1', 'weighted_centroid-0', 'weighted_centroid-1', 'orientation']}

  model_config: {'model_config':{'type':'SimpleClassifier', 'n_output_nodes':9, 'input_dim': 176, 'hidden_dims': [256, 256, 256]},
                       'optimizer_config':{'type':'adam','lr':0.00001, 'weight_decay':0.005},
                       'loss_config':{'type':'ce'}}

  domain_name: 'morph_profile'
  num_epochs: 2000
  early_stopping: 20
  train_val_test_split: [0.7, 0.2, 0.1]
  batch_size: 32
  random_state: 1234
  save_freq: 50

pipeline:
  - method: initialize_profile_data_set
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
  - method: train_models
  - method: visualize_loss_evolution

