output_dir: 'data/experiments/morph_embeddings'
module: src.experiments.train_model
class: TrainModelExperiment
run_params:
  data_config: {'feature_label_file':'data/images/metadata/nuclei_profiles_hoechst_cleaned.csv',
                      'data_key':'profile', 'label_key':'label',
                      'label_col':'labels',
                      'target_list':["ARNTL", "ATG5", "BAX", "CASP8", "CCND1", "CEBPA", "DVL2", "ERG", "JUN"]}

  model_config: {'model_config':{'type':'SimpleClassifier', 'n_output_nodes':9, 'input_dim': 135},
                       'optimizer_config':{'type':'adam','lr':0.0001, 'weight_decay':0.0005},
                       'loss_config':{'type':'ce'}}

  domain_name: 'morph_profile'
  num_epochs: 2000
  early_stopping: 20
  train_val_test_split: [0.7, 0.2, 0.1]
  batch_size: 32
  random_state: 1234
  save_freq: 50

pipeline:
  - method: initialize_profile_data_set
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
  - method: train_models
  - method: visualize_loss_evolution

