output_dir: 'data/experiments/image_embeddings'
module: src.experiments.image_embeddings
class: ImageEmbeddingExperiment
run_params:
  data_config: {'nuclei_image_dir':'data/experiments/image_preprocessing/full_pipeline/padded_nuclei',
                      'nuclei_metadata_file':'data/experiments/image_preprocessing/full_pipeline/padded_nuclei_metadata.csv.gz',
                      'slide_image_dir': 'data/experiments/image_preprocessing/full_pipeline/filtered',
                      'data_key':'images', 'label_key':'label', 'index_key':'image_file',
                      'target_list':['ACVR1B', 'ADAM17', 'AKT1', 'AKT1S1', 'AKT2', 'AKT3', 'APAF1', 'APC', 'ARAF', 'ARNTL', 'ATF2', 'ATF4', 'ATF6', 'ATG16L1', 'ATG5', 'ATM', 'AXIN2', 'BAMBI', 'BAX', 'BCL2L1', 'BCL2L11', 'BECN1', 'BMP2', 'BMPR1B', 'BRAF', 'BRCA1', 'BTRC', 'CARD11', 'CASP8', 'CASP9', 'CCND1', 'CCNE1', 'CDC42', 'CDK2', 'CDK4', 'CDKN1A', 'CEBPA', 'CHUK', 'CLOCK', 'CREB1', 'CREBBP', 'CRY1', 'CSNK1A1', 'CTNNB1', 'CXXC4', 'CYLD', 'DDIT3', 'DDIT4', 'DEPTOR', 'DIABLO', 'DKK1', 'DLL1', 'DUSP1', 'DVL1', 'DVL2', 'DVL3', 'E2F1', 'EGLN1', 'EIF2A', 'EIF4E', 'EIF4EBP1', 'ELK1', 'ERBB2', 'ERG', 'ERN1', 'FGFR3', 'FH', 'FOXO1', 'FURIN', 'GLI1', 'GRB10', 'GSK3B', 'HIF1A', 'HIF1AN', 'HRAS', 'HSP90AA1', 'HSP90B1', 'HSPA5', 'IKBKB', 'IKBKE', 'IRAK1', 'IRAK4', 'IRS1', 'JAG1', 'JAK2', 'JUN', 'KRAS', 'LRPPRC', 'MAP2K1', 'MAP2K3', 'MAP2K4', 'MAP3K11', 'MAP3K2', 'MAP3K5', 'MAP3K7', 'MAP3K8', 'MAP3K9', 'MAPK1', 'MAPK13', 'MAPK14', 'MAPK3', 'MAPK7', 'MAPK8', 'MAPK9', 'MAPKAP1', 'MCL1', 'MKNK1', 'MLST8', 'MYD88', 'NFKB1', 'NFKB2', 'NFKBIA', 'NFKBIB', 'NFKBIE', 'NOTCH1', 'NOTCH2', 'PAK1', 'PDPK1', 'PER1', 'PHLPP1', 'PIK3CA', 'PIK3CB', 'PIK3CD', 'PIK3R1', 'PIK3R2', 'PKIA', 'PPARGC1A', 'PPP2R5C', 'PRKAA1', 'PRKACA', 'PRKACB', 'PRKCA', 'PRKCE', 'PRKCZ', 'PSENEN', 'PTEN', 'RAC1', 'RAF1', 'RB1', 'RBPJ', 'REL', 'RELA', 'RELB', 'RHEB', 'RHOA', 'RICTOR', 'RIPK1', 'RPS6KB1', 'RPTOR', 'SDHA', 'SGK3', 'SLIRP', 'SMAD3', 'SMAD4', 'SMAD5', 'SMAD7', 'SMO', 'SMURF2', 'SOCS3', 'SRC', 'SREBF1', 'STAT1', 'STAT3', 'STK11', 'STK3', 'TBK1', 'TCF4', 'TGFB1', 'TGFBR1', 'TGFBR2', 'TNFAIP3', 'TP53', 'TRAF2', 'TRAF3', 'TRAF5', 'TRAF6', 'TSC1', 'TSC2', 'VEGFC', 'VHL', 'WNT5A', 'WWTR1', 'XBP1', 'XIAP', 'YAP1'],
                      'pseudo_rgb':True}

  model_config: {'model_config':{
                        'type':'ensemble',
                        'input_dim': 512,
                        'latent_dim': 256,
                        'n_output_nodes': 185,
                        'component_dicts':[
                                {'type':'ResNet18', 'pretrained':True, 'n_output_nodes':128,
                                 fix_feature_extractor: False, 'dropout_rate':0.0},
                                {'type':'ResNet18', 'pretrained':True, 'n_output_nodes':128,
                                 fix_feature_extractor: False, 'dropout_rate':0.0}
                        ]
                 },
                 'optimizer_config':{'type':'adam','lr':0.00001, 'weight_decay':0.005},
                 'loss_config':{'type':'ce'}}

  domain_name: 'image'
  num_epochs: 300
  early_stopping: 20
  train_val_test_split: [0.6, 0.2, 0.2]
  batch_size: 64
  random_state: 1234
  save_freq: 50

pipeline:
  - method: initialize_image_data_set
    params:
      multi_image: True
  - method: initialize_data_transform_pipeline
    params:
      data_transform_pipelines: ["nuclei_image", "slide_image"]
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
  - method: train_models
  - method: evaluate_test_performance
  - method: visualize_loss_evolution

